In [11]:
import pandas as pd
import numpy as np
#   NumPyのLinalgモジュールの読み込み
import numpy.linalg as lin
#   SciPyのoptimizeモジュールの読み込み
import scipy.optimize as opt
#%% リスク寄与度の平準化によるポートフォリオ選択
Data = pd.read_csv('190124_Nakatsuma_Finalreport_alldata.csv', index_col=0)
R = Data.fillna(0)
Mu = R.mean().values
Stdev = R.std().values
CorrMatrix = R.corr()
Sigma = np.diag(Stdev).dot(CorrMatrix).dot(np.diag(Stdev))
iota = np.ones(Mu.shape)
inv_Sigma = lin.inv(Sigma)
Weight_1N = np.tile(1.0/Mu.shape[0], Mu.shape[0])
Weight_MV = inv_Sigma.dot(iota) / iota.dot(inv_Sigma).dot(iota)
Weight_MD = inv_Sigma.dot(Stdev) / iota.dot(inv_Sigma).dot(Stdev)
F = lambda v, Sigma: np.r_[Sigma.dot(v[:-1])-v[-1]/v[:-1], v[:-1].sum()-1.0]
Weight_RP = opt.root(F, np.r_[Weight_1N, 0.0], args=Sigma).x[:-1]
np.set_printoptions(formatter={'float': '{:7.2f}'.format})
print(np.c_[Weight_1N, Weight_MV, Weight_RP, Weight_MD]*100)

[[  10.00   16.61   10.45   18.32]
 [  10.00    6.14    9.53    8.02]
 [  10.00   -2.82    6.92    4.57]
 [  10.00    1.61    8.69   13.31]
 [  10.00   13.50    8.47   -5.66]
 [  10.00  -11.60    7.32  -15.97]
 [  10.00  -12.79    6.87   11.84]
 [  10.00   -2.06    8.69   16.22]
 [  10.00   76.67   20.39   28.79]
 [  10.00   14.73   12.66   20.55]]
